Initial creation of plugins included OpenTimelineIO package
OpenTimelineIO/OpenTimelineIO-Plugins pull request #1
Opened 2023-07-07 23:48 UTC by reinecke

This introduces a new python package that:

- refers to a specific OpenTimelineIO version (uses the git branch with adapters removed)
- points to adapter plugins in PyPI

Marked as draft because it's pointing to git rather than a 0.16.0.devX release of OpenTimelineIO.

2023-07-07 23:57 UTC, JeanChristopheMorinPerso requested changes

2023-07-07 23:57 UTC, JeanChristopheMorinPerso commented on pyproject.toml
> +name = "otio-svg-adapter"
it should be `opentimeline-plugins`

2023-07-08 15:46 UTC, JeanChristopheMorinPerso commented
Would it be a good idea to list the included plugins in the README? This could easily be automated by extracting them from the `pyproject.toml` file.

2023-10-05 21:55 UTC, reinecke commented
I think this is ready to send - in a subsequent PR I'll re-add the plugin dependencies for the 0.17.0dev1 release.

2023-10-06 16:16 UTC, JeanChristopheMorinPerso approved these changes

2023-10-06 18:49 UTC, merged